### ISSUE TITLE
`doctest` fails to build on `windows-latest` in `wai`'s CI

### ISSUE THREAD

**Issue by Vlix** [sol/doctest#458]
```
doctest > C:/Users/runneradmin/AppData/Local/Programs/stack/x86_64-windows/ghc-9.8.3/mingw/bin/strip.exe: error: Permission denied
```

This happened in the `wai` GitHub action https://github.com/yesodweb/wai/actions/runs/11540316417/job/32121009548?pr=996

Using the following CI: https://github.com/yesodweb/wai/blob/master/.github/workflows/tests.yml

```yaml
os: "windows-latest"
stack: "latest"
resolver: "--resolver nightly --stack-yaml stack-nightly.yaml"
```

Any idea why this would happen only on the nightly build?
The other jobs ran fine (with only a different resolver and `stack.yaml`)
